-- =============================================================================
-- TradingAI — SUPABASE ONE-SHOT BUNDLE
-- Generated by concatenating every migration in order. Paste this entire file
-- into the Supabase SQL Editor and run once for a fresh deploy.
-- Idempotent: every CREATE uses 'if not exists', every CREATE POLICY is
-- guarded by a do-block, every column-add is guarded by information_schema.
-- Re-running this on an existing schema is safe (no-ops everywhere).
-- =============================================================================


-- ---------- 001_init.sql ----------
-- TradingAI initial schema
-- =============================================================================
-- Run order matters. Tables created here, RLS enabled, policies set in same file.
-- Every user-owned table MUST have a user_id column and RLS using auth.uid().
-- =============================================================================

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;
create extension if not exists vector;

-- -----------------------------------------------------------------------------
-- Token registry (canonical, shared across users)
-- -----------------------------------------------------------------------------
create table if not exists tokens (
    id          uuid primary key default uuid_generate_v4(),
    coingecko_id text unique,
    chain       text not null,             -- 'ethereum', 'solana', 'bsc', ...
    address     text,                       -- null for native (BTC, ETH on mainnet)
    symbol      text not null,
    name        text not null,
    decimals    int,
    market_cap_rank int,
    metadata    jsonb default '{}',
    created_at  timestamptz default now(),
    updated_at  timestamptz default now(),
    unique (chain, address)
);
create index if not exists tokens_symbol_idx on tokens (symbol);

-- -----------------------------------------------------------------------------
-- Invitations (closed signup)
-- -----------------------------------------------------------------------------
create table if not exists invites (
    code        text primary key,
    issued_by   uuid references auth.users(id),
    used_by     uuid references auth.users(id),
    used_at     timestamptz,
    expires_at  timestamptz,
    note        text,
    created_at  timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- Watchlists
-- -----------------------------------------------------------------------------
create table if not exists watchlists (
    id          uuid primary key default uuid_generate_v4(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    name        text not null,
    sort_order  int default 0,
    created_at  timestamptz default now()
);
create index if not exists watchlists_user_idx on watchlists (user_id);

create table if not exists watchlist_items (
    id            uuid primary key default uuid_generate_v4(),
    watchlist_id  uuid not null references watchlists(id) on delete cascade,
    token_id      uuid not null references tokens(id),
    sort_order    int default 0,
    added_at      timestamptz default now(),
    unique (watchlist_id, token_id)
);
create index if not exists watchlist_items_watchlist_idx on watchlist_items (watchlist_id);

-- -----------------------------------------------------------------------------
-- Time-series: prices, sentiment, news
-- -----------------------------------------------------------------------------
create table if not exists price_ticks (
    token_id   uuid not null references tokens(id),
    ts         timestamptz not null,
    price_usd  numeric(20, 8) not null,
    market_cap numeric(20, 2),
    volume_24h numeric(20, 2),
    source     text not null default 'coingecko',
    primary key (token_id, ts, source)
);
create index if not exists price_ticks_token_ts_idx on price_ticks (token_id, ts desc);

create table if not exists sentiment_ticks (
    token_id        uuid not null references tokens(id),
    ts              timestamptz not null,
    social_volume   numeric,
    sentiment_score numeric,            -- -1..1
    source          text not null default 'lunarcrush',
    raw             jsonb,
    primary key (token_id, ts, source)
);

create table if not exists news_items (
    id          uuid primary key default uuid_generate_v4(),
    token_id    uuid references tokens(id),
    ts          timestamptz not null,
    title       text not null,
    url         text not null unique,
    source      text not null,
    summary     text,
    raw         jsonb
);
create index if not exists news_items_token_ts_idx on news_items (token_id, ts desc);

-- -----------------------------------------------------------------------------
-- Briefs (AI-generated research)
-- -----------------------------------------------------------------------------
create table if not exists briefs (
    id          uuid primary key default uuid_generate_v4(),
    token_id    uuid not null references tokens(id),
    user_id     uuid references auth.users(id) on delete set null,  -- null = shared scheduled brief
    horizon     text not null check (horizon in ('swing', 'position', 'long')),
    prompt_id   text not null,                                       -- e.g., 'token-brief-v3'
    llm_provider text not null,
    llm_model   text not null,
    structured  jsonb not null,         -- conforms to TokenBriefSchema
    markdown    text not null,
    sources     jsonb not null default '[]',
    confidence  numeric,
    created_at  timestamptz default now()
);
create index if not exists briefs_token_idx on briefs (token_id, created_at desc);
create index if not exists briefs_user_idx on briefs (user_id, created_at desc);

-- -----------------------------------------------------------------------------
-- Theses
-- -----------------------------------------------------------------------------
create table if not exists theses (
    id              uuid primary key default uuid_generate_v4(),
    user_id         uuid not null references auth.users(id) on delete cascade,
    token_id        uuid not null references tokens(id),
    stance          text not null check (stance in ('bullish', 'bearish')),
    horizon         text not null check (horizon in ('swing', 'position', 'long')),
    core_thesis     text not null,
    key_assumptions jsonb not null default '[]',
    invalidation    jsonb not null default '[]',
    review_cadence  text not null default 'weekly',
    status          text not null default 'open' check (status in ('open', 'closed', 'invalidated')),
    opened_at       timestamptz default now(),
    closed_at       timestamptz
);
create index if not exists theses_user_token_idx on theses (user_id, token_id);

create table if not exists thesis_evaluations (
    id           uuid primary key default uuid_generate_v4(),
    thesis_id    uuid not null references theses(id) on delete cascade,
    ts           timestamptz default now(),
    overall      text not null check (overall in ('healthy', 'drifting', 'under_stress', 'invalidated')),
    per_assumption jsonb not null default '[]',
    per_invalidation jsonb not null default '[]',
    notes        text
);
create index if not exists thesis_evals_thesis_idx on thesis_evaluations (thesis_id, ts desc);

-- -----------------------------------------------------------------------------
-- Alerts
-- -----------------------------------------------------------------------------
create table if not exists alert_rules (
    id          uuid primary key default uuid_generate_v4(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    token_id    uuid references tokens(id),
    rule_type   text not null,                  -- 'price_threshold', 'pct_move', 'funding_flip', ...
    config      jsonb not null,                 -- rule-specific knobs
    severity    text not null default 'info' check (severity in ('info', 'warn', 'critical')),
    enabled     boolean not null default true,
    created_at  timestamptz default now()
);
create index if not exists alert_rules_user_idx on alert_rules (user_id);

create table if not exists alerts (
    id          uuid primary key default uuid_generate_v4(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    rule_id     uuid references alert_rules(id) on delete set null,
    token_id    uuid references tokens(id),
    severity    text not null,
    title       text not null,
    body        text,
    payload     jsonb,
    status      text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'snoozed')),
    fired_at    timestamptz default now(),
    delivered_at timestamptz,
    read_at     timestamptz
);
create index if not exists alerts_user_idx on alerts (user_id, fired_at desc);
create index if not exists alerts_status_idx on alerts (status) where status = 'pending';

-- -----------------------------------------------------------------------------
-- Exchange keys (encrypted at rest via Supabase Vault in prod)
-- For local dev, this table holds plaintext — DO NOT use for prod.
-- -----------------------------------------------------------------------------
create table if not exists exchange_keys (
    id          uuid primary key default uuid_generate_v4(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    exchange    text not null,                  -- 'binance', 'coinbase', 'kraken', ...
    label       text,
    encrypted_key bytea,                        -- pgsodium / Vault encrypted
    encrypted_secret bytea,
    permissions text[] not null default '{read}',
    created_at  timestamptz default now(),
    last_used_at timestamptz
);

create table if not exists holdings (
    id          uuid primary key default uuid_generate_v4(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    exchange_key_id uuid references exchange_keys(id) on delete cascade,
    token_id    uuid not null references tokens(id),
    quantity    numeric(40, 18) not null,
    avg_cost_usd numeric(20, 8),
    snapshot_ts timestamptz default now()
);
create index if not exists holdings_user_idx on holdings (user_id, snapshot_ts desc);

-- -----------------------------------------------------------------------------
-- AI calls (track-record / backtest input)
-- -----------------------------------------------------------------------------
create table if not exists ai_calls (
    id              uuid primary key default uuid_generate_v4(),
    user_id         uuid references auth.users(id) on delete set null,
    token_id        uuid references tokens(id),
    call_type       text not null,              -- 'brief', 'alert', 'thesis_check'
    claim           jsonb not null,             -- structured: {direction, magnitude, horizon}
    confidence      numeric,
    horizon_seconds int,
    created_at      timestamptz default now(),
    evaluated_at    timestamptz,
    outcome         text,                        -- 'correct', 'wrong', 'inconclusive', 'insufficient_sample'
    outcome_meta    jsonb
);
create index if not exists ai_calls_unevaluated_idx on ai_calls (created_at) where evaluated_at is null;

-- -----------------------------------------------------------------------------
-- Audit log
-- -----------------------------------------------------------------------------
create table if not exists audit_log (
    id          bigserial primary key,
    user_id     uuid references auth.users(id) on delete set null,
    actor       text not null default 'system',     -- 'user', 'system', 'agent'
    action      text not null,
    target      text,
    args_summary jsonb,
    result_summary jsonb,
    ts          timestamptz default now()
);
create index if not exists audit_log_user_ts_idx on audit_log (user_id, ts desc);

-- =============================================================================
-- Row Level Security
-- =============================================================================
alter table watchlists       enable row level security;
alter table watchlist_items  enable row level security;
alter table briefs           enable row level security;
alter table theses           enable row level security;
alter table thesis_evaluations enable row level security;
alter table alert_rules      enable row level security;
alter table alerts           enable row level security;
alter table exchange_keys    enable row level security;
alter table holdings         enable row level security;
alter table ai_calls         enable row level security;
alter table audit_log        enable row level security;

-- Watchlists
create policy "watchlists self" on watchlists
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "watchlist_items via watchlist" on watchlist_items
    for all using (
        exists (select 1 from watchlists w where w.id = watchlist_items.watchlist_id and w.user_id = auth.uid())
    );

-- Briefs (briefs with user_id = null are public-shared scheduled briefs; otherwise user-scoped)
create policy "briefs read self or shared" on briefs
    for select using (user_id is null or user_id = auth.uid());
create policy "briefs write self" on briefs
    for insert with check (user_id = auth.uid() or user_id is null);

-- Theses
create policy "theses self" on theses
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "thesis_evals via thesis" on thesis_evaluations
    for all using (
        exists (select 1 from theses t where t.id = thesis_evaluations.thesis_id and t.user_id = auth.uid())
    );

-- Alerts
create policy "alert_rules self" on alert_rules
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "alerts self" on alerts
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Exchange keys & holdings
create policy "exchange_keys self" on exchange_keys
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "holdings self" on holdings
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- AI calls (per-user; null user_id rows are global)
create policy "ai_calls read self or global" on ai_calls
    for select using (user_id is null or user_id = auth.uid());

-- Audit log: user can read own; only service_role writes
create policy "audit_log read self" on audit_log
    for select using (user_id = auth.uid());

-- =============================================================================
-- Triggers
-- =============================================================================
create or replace function touch_updated_at() returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger tokens_touch before update on tokens
    for each row execute function touch_updated_at();

-- ---------- 002_backtest.sql ----------
-- TradingAI — backtest schema
-- =============================================================================
-- Adds historical OHLCV storage + backtest run tracking + indicator signals.
-- Designed for 4 years × top 250 tokens × 1h+1d resolution =
--   ~ 35k bars/token/timeframe × 250 tokens × 2 timeframes ≈ 17.5M rows total.
-- Standard B-tree indexes are fine at this scale; revisit hypertables if it grows.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Historical OHLCV (separate from live `price_ticks` for cleaner access)
-- -----------------------------------------------------------------------------
create table if not exists historical_ohlcv (
    token_id   uuid not null references tokens(id),
    exchange   text not null,                          -- 'binance', 'kraken', ...
    pair       text not null,                          -- 'BTC/USDT'
    timeframe  text not null check (timeframe in ('1m','5m','15m','30m','1h','4h','1d','1w')),
    ts         timestamptz not null,
    open       numeric(24, 12) not null,
    high       numeric(24, 12) not null,
    low        numeric(24, 12) not null,
    close      numeric(24, 12) not null,
    volume     numeric(28, 12) not null,
    primary key (token_id, exchange, pair, timeframe, ts)
);
create index if not exists historical_ohlcv_token_tf_ts on historical_ohlcv (token_id, timeframe, ts desc);
create index if not exists historical_ohlcv_pair_tf_ts on historical_ohlcv (pair, timeframe, ts desc);

-- -----------------------------------------------------------------------------
-- Backfill cursor — what's the most recent bar we have per (token, exchange, tf)?
-- -----------------------------------------------------------------------------
create table if not exists historical_cursor (
    token_id   uuid not null references tokens(id),
    exchange   text not null,
    pair       text not null,
    timeframe  text not null,
    last_ts    timestamptz,
    last_run_at timestamptz default now(),
    rows_total int default 0,
    note       text,
    primary key (token_id, exchange, pair, timeframe)
);

-- -----------------------------------------------------------------------------
-- Indicator snapshots — latest computed values per (token, timeframe).
-- Useful for the dashboard headline + as-of-time backtest replay.
-- -----------------------------------------------------------------------------
create table if not exists indicator_snapshots (
    token_id   uuid not null references tokens(id),
    timeframe  text not null,
    as_of      timestamptz not null,
    regime     text,
    payload    jsonb not null,            -- the IndicatorSnapshot.as_dict()
    primary key (token_id, timeframe, as_of)
);

-- -----------------------------------------------------------------------------
-- Pattern hits — append-only history of detected chart/divergence patterns.
-- -----------------------------------------------------------------------------
create table if not exists pattern_hits (
    id          uuid primary key default uuid_generate_v4(),
    token_id    uuid not null references tokens(id),
    timeframe   text not null,
    detected_at timestamptz not null,
    kind        text not null,
    confidence  numeric,
    target      numeric,
    payload     jsonb,
    created_at  timestamptz default now()
);
create index if not exists pattern_hits_token_tf_ts on pattern_hits (token_id, timeframe, detected_at desc);
create index if not exists pattern_hits_kind_idx on pattern_hits (kind);

-- -----------------------------------------------------------------------------
-- Backtest runs + per-trade results
-- -----------------------------------------------------------------------------
create table if not exists backtest_runs (
    id              uuid primary key default uuid_generate_v4(),
    user_id         uuid references auth.users(id) on delete set null,  -- null = global
    name            text not null,                                       -- 'rsi-mean-reversion-v1'
    strategy_kind   text not null,                                       -- 'indicator' | 'llm-sample' | 'llm-forward'
    universe        text[] not null,                                     -- list of symbols / coingecko ids
    timeframe       text not null,
    start_ts        timestamptz not null,
    end_ts          timestamptz not null,
    params          jsonb not null default '{}',                         -- strategy-specific
    status          text not null default 'pending'
                    check (status in ('pending','running','completed','failed')),
    metrics         jsonb,                                               -- summary numbers
    created_at      timestamptz default now(),
    started_at      timestamptz,
    finished_at     timestamptz
);
create index if not exists backtest_runs_user_idx on backtest_runs (user_id, created_at desc);

create table if not exists backtest_trades (
    id          uuid primary key default uuid_generate_v4(),
    run_id      uuid not null references backtest_runs(id) on delete cascade,
    token_id    uuid references tokens(id),
    symbol      text not null,
    direction   text not null check (direction in ('long','short')),
    entry_ts    timestamptz not null,
    entry_price numeric not null,
    exit_ts     timestamptz,
    exit_price  numeric,
    pnl_pct     numeric,
    holding_hours int,
    rationale   jsonb                                          -- which indicator/signal opened it
);
create index if not exists backtest_trades_run_idx on backtest_trades (run_id);

-- -----------------------------------------------------------------------------
-- LLM-sample backtest support: pick "interesting" historical moments per token
-- so we burn API budget on the moments that matter.
-- -----------------------------------------------------------------------------
create table if not exists historical_decision_points (
    id            uuid primary key default uuid_generate_v4(),
    token_id      uuid not null references tokens(id),
    timeframe     text not null,
    ts            timestamptz not null,
    reason        text not null,        -- 'regime_change', 'big_move', 'pattern_complete', 'macro_event'
    metadata      jsonb,
    created_at    timestamptz default now(),
    unique (token_id, timeframe, ts)
);
create index if not exists hdp_token_tf_idx on historical_decision_points (token_id, timeframe, ts desc);

-- -----------------------------------------------------------------------------
-- RLS — backtests are visible to the user that owns them; null user_id = shared.
-- -----------------------------------------------------------------------------
alter table backtest_runs   enable row level security;
alter table backtest_trades enable row level security;

create policy "backtest_runs read self or shared" on backtest_runs
    for select using (user_id is null or user_id = auth.uid());
create policy "backtest_runs write self" on backtest_runs
    for insert with check (user_id = auth.uid() or user_id is null);
create policy "backtest_runs update own" on backtest_runs
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "backtest_trades via run" on backtest_trades
    for select using (
        exists (
            select 1 from backtest_runs r
            where r.id = backtest_trades.run_id
              and (r.user_id is null or r.user_id = auth.uid())
        )
    );

-- ---------- 003_user_extras.sql ----------
-- =============================================================================
-- 003 — user extras + kill switch + telegram link
-- =============================================================================

-- Per-user profile sidecar (we don't touch auth.users directly).
create table if not exists user_profiles (
    user_id          uuid primary key references auth.users(id) on delete cascade,
    display_name     text,
    telegram_chat_id text,
    telegram_username text,
    timezone         text default 'UTC',
    notifications_paused_until timestamptz,
    created_at       timestamptz default now(),
    updated_at       timestamptz default now()
);

create index if not exists user_profiles_telegram_idx
    on user_profiles (telegram_chat_id) where telegram_chat_id is not null;

alter table user_profiles enable row level security;

create policy "user_profiles self read" on user_profiles
    for select using (user_id = auth.uid());
create policy "user_profiles self upsert" on user_profiles
    for insert with check (user_id = auth.uid());
create policy "user_profiles self update" on user_profiles
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Pending Telegram link codes — short-lived one-time codes minted in the web app
create table if not exists telegram_link_codes (
    code        text primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    expires_at  timestamptz not null,
    used_at     timestamptz,
    created_at  timestamptz default now()
);
create index if not exists telegram_link_codes_user_idx
    on telegram_link_codes (user_id);

alter table telegram_link_codes enable row level security;
create policy "telegram_link_codes self" on telegram_link_codes
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Global system flags (kill switch lives here)
create table if not exists system_flags (
    key   text primary key,
    value jsonb not null,
    updated_at timestamptz default now()
);

insert into system_flags (key, value) values
    ('llm_killswitch', 'false'::jsonb),
    ('alerts_killswitch', 'false'::jsonb)
on conflict (key) do nothing;

-- Trigger: keep updated_at fresh
create or replace function touch_user_profile() returns trigger as $$
begin new.updated_at = now(); return new; end; $$ language plpgsql;
create trigger user_profiles_touch before update on user_profiles
    for each row execute function touch_user_profile();

-- ---------- 004_rls_audit.sql ----------
-- =============================================================================
-- 004 — RLS audit + defensive rewrites
--
-- Purpose:
--   1. Eliminate any chance of `42P17 infinite recursion detected in policy`.
--   2. Provide a queryable audit view for current RLS policies.
--   3. Provide a function that tests the recursion-detector at runtime.
--
-- Run this AFTER 001/003. It is idempotent — safe to re-run.
-- =============================================================================

-- ---------- Defensive rewrite: user_profiles policies ------------------------
-- We drop ALL existing user_profiles policies (regardless of who created them
-- in the Supabase dashboard) and re-create the minimal, non-recursive set.

do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles'
  loop
    execute format('drop policy if exists %I on public.user_profiles', p.policyname);
  end loop;
end $$;

-- Each policy uses ONLY auth.uid() — no cross-table subqueries, no self-SELECT.
create policy "user_profiles select self" on public.user_profiles
  for select using (user_id = auth.uid());

create policy "user_profiles insert self" on public.user_profiles
  for insert with check (user_id = auth.uid());

create policy "user_profiles update self" on public.user_profiles
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "user_profiles delete self" on public.user_profiles
  for delete using (user_id = auth.uid());

-- ---------- Audit views -------------------------------------------------------
-- View: every RLS policy in the public schema with the SQL of its USING/WITH CHECK
-- clauses, so you can spot subqueries against other RLS-protected tables.
create or replace view rls_policy_audit as
select
  schemaname,
  tablename,
  policyname,
  cmd        as command,
  permissive,
  roles,
  qual       as using_clause,
  with_check
from pg_policies
where schemaname = 'public'
order by tablename, policyname;

-- View: tables with RLS enabled in public schema
create or replace view rls_enabled_tables as
select
  c.relname as table_name,
  c.relrowsecurity as rls_enabled,
  (select count(*) from pg_policies p
     where p.schemaname = 'public' and p.tablename = c.relname) as policy_count
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind = 'r'
order by c.relname;

-- ---------- Heuristic: flag policies that subquery another RLS-protected table -
-- A policy that contains "from public.<other_table>" where <other_table> also has
-- RLS enabled is a recursion candidate. This is heuristic — it doesn't guarantee
-- recursion, but it surfaces the patterns to review.
create or replace view rls_recursion_candidates as
with rls_tables as (
  select c.relname as t
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
policy_clauses as (
  select schemaname, tablename, policyname,
         coalesce(qual::text, '') || ' ' || coalesce(with_check::text, '') as clause
    from pg_policies
   where schemaname = 'public'
)
select pc.tablename, pc.policyname, rt.t as references_rls_table, pc.clause
  from policy_clauses pc
  join rls_tables rt on pc.clause ilike '%' || rt.t || '%'
                     and pc.tablename <> rt.t  -- self-references handled separately
order by pc.tablename, pc.policyname;

-- ---------- Self-reference detector ------------------------------------------
create or replace view rls_self_reference_candidates as
select schemaname, tablename, policyname,
       coalesce(qual::text, '') || ' ' || coalesce(with_check::text, '') as clause
  from pg_policies
 where schemaname = 'public'
   and (coalesce(qual::text, '') ilike '%from ' || tablename || '%'
        or coalesce(with_check::text, '') ilike '%from ' || tablename || '%')
order by tablename, policyname;

-- ---------- Helper function: list problematic policies in one call ------------
create or replace function rls_audit() returns table(kind text, location text, detail text)
language sql stable as $$
  select 'self-reference', tablename || '.' || policyname, clause
    from rls_self_reference_candidates
  union all
  select 'cross-RLS-reference', tablename || '.' || policyname,
         'references RLS-enabled table: ' || references_rls_table
    from rls_recursion_candidates;
$$;

comment on function rls_audit is
  'Run "select * from rls_audit()" to surface any policy that may cause '
  'infinite-recursion errors. Reports self-references and cross-table RLS subqueries.';

-- ---------- 005_pgvector_rag.sql ----------
-- =============================================================================
-- 005 — pgvector RAG: brief + thesis embeddings, similarity search
-- =============================================================================

create extension if not exists vector;

-- Add embedding column to briefs (1536 dims = OpenAI text-embedding-3-large default)
alter table briefs add column if not exists embedding vector(1536);
create index if not exists briefs_embedding_idx
  on briefs using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Same for theses (we embed the core_thesis + assumptions + invalidation)
alter table theses add column if not exists embedding vector(1536);
create index if not exists theses_embedding_idx
  on theses using ivfflat (embedding vector_cosine_ops) with (lists = 50);

-- News items get embedded for narrative-cluster retrieval
alter table news_items add column if not exists embedding vector(1536);
create index if not exists news_items_embedding_idx
  on news_items using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Helper: top-K similar past briefs for a given user × token (auth.uid() default)
create or replace function similar_briefs(
  query_embedding vector(1536),
  for_user uuid,
  for_token uuid default null,
  k int default 5
)
returns table (
  id uuid, token_id uuid, horizon text, markdown text,
  similarity float, created_at timestamptz
) language sql stable as $$
  select b.id, b.token_id, b.horizon, b.markdown,
         1 - (b.embedding <=> query_embedding) as similarity,
         b.created_at
    from briefs b
   where (b.user_id = for_user or b.user_id is null)
     and b.embedding is not null
     and (for_token is null or b.token_id = for_token)
   order by b.embedding <=> query_embedding
   limit k;
$$;

-- ---------- 006_security_hardening.sql ----------
-- =============================================================================
-- 006 — Security hardening from Supabase advisor findings
--
-- Fixes:
--   1. ERROR: 4 audit views were SECURITY DEFINER by default → switch to INVOKER
--      so RLS audits reflect the calling user's permissions, not the creator's.
--   2. WARN: 4 functions had a mutable search_path (search-path-injection risk)
--      → pin to ``public, pg_temp``.
-- =============================================================================

drop view if exists rls_policy_audit;
drop view if exists rls_enabled_tables;
drop view if exists rls_recursion_candidates;
drop view if exists rls_self_reference_candidates;

create view rls_policy_audit
  with (security_invoker = true) as
select
  schemaname, tablename, policyname,
  cmd as command, permissive, roles,
  qual as using_clause, with_check
from pg_policies
where schemaname = 'public'
order by tablename, policyname;

create view rls_enabled_tables
  with (security_invoker = true) as
select
  c.relname as table_name,
  c.relrowsecurity as rls_enabled,
  (select count(*) from pg_policies p
     where p.schemaname = 'public' and p.tablename = c.relname) as policy_count
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind = 'r'
order by c.relname;

create view rls_recursion_candidates
  with (security_invoker = true) as
with rls_tables as (
  select c.relname as t
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
policy_clauses as (
  select schemaname, tablename, policyname,
         coalesce(qual::text, '') || ' ' || coalesce(with_check::text, '') as clause
    from pg_policies
   where schemaname = 'public'
)
select pc.tablename, pc.policyname, rt.t as references_rls_table, pc.clause
  from policy_clauses pc
  join rls_tables rt on pc.clause ilike '%' || rt.t || '%'
                     and pc.tablename <> rt.t
order by pc.tablename, pc.policyname;

create view rls_self_reference_candidates
  with (security_invoker = true) as
select schemaname, tablename, policyname,
       coalesce(qual::text, '') || ' ' || coalesce(with_check::text, '') as clause
  from pg_policies
 where schemaname = 'public'
   and (coalesce(qual::text, '') ilike '%from ' || tablename || '%'
        or coalesce(with_check::text, '') ilike '%from ' || tablename || '%')
order by tablename, policyname;

create or replace function rls_audit() returns table(kind text, location text, detail text)
language sql stable
set search_path = public, pg_temp
as $$
  select 'self-reference', tablename || '.' || policyname, clause
    from rls_self_reference_candidates
  union all
  select 'cross-RLS-reference', tablename || '.' || policyname,
         'references RLS-enabled table: ' || references_rls_table
    from rls_recursion_candidates;
$$;

create or replace function touch_updated_at() returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function touch_user_profile() returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin new.updated_at = now(); return new; end;
$$;

create or replace function similar_briefs(
  query_embedding vector(1536),
  for_user uuid,
  for_token uuid default null,
  k int default 5
)
returns table (
  id uuid, token_id uuid, horizon text, markdown text,
  similarity float, created_at timestamptz
) language sql stable
set search_path = public, pg_temp
as $$
  select b.id, b.token_id, b.horizon, b.markdown,
         1 - (b.embedding <=> query_embedding) as similarity,
         b.created_at
    from briefs b
   where (b.user_id = for_user or b.user_id is null)
     and b.embedding is not null
     and (for_token is null or b.token_id = for_token)
   order by b.embedding <=> query_embedding
   limit k;
$$;

-- ---------- 007_public_reference_reads.sql ----------
-- =============================================================================
-- 007 — Public-read policies for canonical reference tables
--
-- ``tokens`` and ``news_items`` hold no PII and are shared/canonical data.
-- Allow any authenticated session to read them so the frontend can join
-- without round-tripping through the backend.
-- =============================================================================

create policy "tokens public read" on tokens
  for select using (true);

create policy "news_items public read" on news_items
  for select using (true);

-- ---------- 008_daily_picks.sql ----------
-- =============================================================================
-- 008 — Daily top-10 picks
-- =============================================================================

create table if not exists daily_pick_runs (
    id            uuid primary key default uuid_generate_v4(),
    run_date      date not null unique,
    started_at    timestamptz default now(),
    finished_at   timestamptz,
    status        text not null default 'running'
                  check (status in ('running','completed','failed','partial')),
    n_scanned     int default 0,
    n_picked      int default 0,
    notes         text,
    metadata      jsonb default '{}'
);

create table if not exists daily_picks (
    id              uuid primary key default uuid_generate_v4(),
    run_id          uuid not null references daily_pick_runs(id) on delete cascade,
    run_date        date not null,
    rank            int not null check (rank between 1 and 50),
    token_id        uuid references tokens(id),
    symbol          text not null,
    pair            text not null,
    direction       text not null check (direction in ('long','short','neutral')),
    composite_score numeric not null,
    confidence      numeric,
    components      jsonb not null default '{}',
    rationale       jsonb not null default '[]',
    suggested_stop  numeric,
    suggested_target numeric,
    risk_reward     numeric,
    last_price      numeric,
    timeframe       text not null default '1d',
    brief_id        uuid references briefs(id) on delete set null,
    created_at      timestamptz default now(),
    unique (run_id, rank)
);
create index if not exists daily_picks_run_date_rank
    on daily_picks (run_date desc, rank);
create index if not exists daily_picks_token_idx
    on daily_picks (token_id, run_date desc);

-- Public read on daily_picks so the frontend can render without a per-user filter.
-- These are admin-curated, system-generated lists; no PII.
alter table daily_pick_runs enable row level security;
alter table daily_picks enable row level security;

create policy "daily_pick_runs public read" on daily_pick_runs
  for select using (true);
create policy "daily_picks public read" on daily_picks
  for select using (true);

-- ---------- 009_gossip_events.sql ----------
-- =============================================================================
-- 009 — Gossip Room: unified event feed of news, social, on-chain, macro,
-- influencer mentions, whale moves. Plus a curated influencer handle list.
-- =============================================================================

create table if not exists gossip_events (
    id            uuid primary key default uuid_generate_v4(),
    ts            timestamptz not null,
    kind          text not null check (kind in ('news','social','onchain','macro','influencer','whale','event')),
    source        text not null,
    title         text not null,
    url           text,
    summary       text,
    tags          text[] not null default '{}',
    impact        int not null default 0 check (impact between 0 and 10),
    token_symbols text[] not null default '{}',
    payload       jsonb default '{}',
    dedupe_key    text unique,
    created_at    timestamptz default now()
);
create index if not exists gossip_events_ts_idx     on gossip_events (ts desc);
create index if not exists gossip_events_kind_idx   on gossip_events (kind);
create index if not exists gossip_events_impact_idx on gossip_events (impact desc);
create index if not exists gossip_events_tokens_idx on gossip_events using gin (token_symbols);
create index if not exists gossip_events_tags_idx   on gossip_events using gin (tags);

alter table gossip_events enable row level security;
create policy "gossip_events public read" on gossip_events
  for select using (true);

create table if not exists influencer_handles (
    id          uuid primary key default uuid_generate_v4(),
    handle      text not null,
    platform    text not null check (platform in ('twitter','x','telegram','warpcast','youtube')),
    weight      int not null default 5 check (weight between 1 and 10),
    note        text,
    added_at    timestamptz default now(),
    unique (handle, platform)
);
alter table influencer_handles enable row level security;
create policy "influencer_handles public read" on influencer_handles
  for select using (true);

insert into influencer_handles (handle, platform, weight, note) values
  ('VitalikButerin',  'x', 9, 'Ethereum cofounder'),
  ('cz_binance',      'x', 8, 'Binance founder; regulatory + listings'),
  ('saylor',          'x', 7, 'Strategy CEO; BTC narrative'),
  ('elonmusk',        'x', 8, 'Memecoin volatility, BTC mentions'),
  ('aeyakovenko',     'x', 6, 'Solana cofounder'),
  ('punk6529',        'x', 6, 'NFT + market structure'),
  ('BitMEXResearch',  'x', 7, 'Quant research'),
  ('hyblockcapital',  'x', 6, 'Liquidations + funding'),
  ('CryptoCobain',    'x', 5, 'Trading commentary'),
  ('CryptoHayes',     'x', 7, 'BitMEX founder; macro framing')
on conflict (handle, platform) do nothing;

-- ---------- 010_wallet_tracker.sql ----------
-- =============================================================================
-- 010 — Wallet Tracker: smart-money flow tracking
-- =============================================================================

create table if not exists tracked_wallets (
    id            uuid primary key default uuid_generate_v4(),
    user_id       uuid references auth.users(id) on delete cascade,  -- null = global/curated
    chain         text not null check (chain in ('ethereum','polygon','arbitrum','optimism','bsc','base','solana')),
    address       text not null,
    label         text not null,
    category      text check (category in ('whale','smart_money','founder','treasury','vc','exchange','protocol','custom')),
    weight        int not null default 5 check (weight between 1 and 10),
    enabled       boolean not null default true,
    notes         text,
    created_at    timestamptz default now(),
    last_polled_at timestamptz,
    unique (chain, address, user_id)
);
create index if not exists tracked_wallets_user_idx    on tracked_wallets (user_id);
create index if not exists tracked_wallets_enabled_idx on tracked_wallets (enabled) where enabled = true;

create table if not exists wallet_events (
    id            uuid primary key default uuid_generate_v4(),
    wallet_id     uuid not null references tracked_wallets(id) on delete cascade,
    chain         text not null,
    address       text not null,
    tx_hash       text not null,
    block_number  bigint,
    ts            timestamptz not null,
    direction     text not null check (direction in ('in','out','contract')),
    token_symbol  text,
    token_address text,
    amount        numeric(40, 18),
    amount_usd    numeric(28, 2),
    counterparty  text,
    counterparty_label text,
    payload       jsonb default '{}',
    created_at    timestamptz default now(),
    unique (chain, tx_hash, address, token_symbol)
);
create index if not exists wallet_events_wallet_ts on wallet_events (wallet_id, ts desc);
create index if not exists wallet_events_token_ts  on wallet_events (token_symbol, ts desc);

alter table tracked_wallets enable row level security;
alter table wallet_events  enable row level security;

create policy "tracked_wallets read own or global" on tracked_wallets
  for select using (user_id is null or user_id = auth.uid());
create policy "tracked_wallets write own" on tracked_wallets
  for insert with check (user_id = auth.uid());
create policy "tracked_wallets update own" on tracked_wallets
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracked_wallets delete own" on tracked_wallets
  for delete using (user_id = auth.uid());

create policy "wallet_events public read" on wallet_events
  for select using (true);

insert into tracked_wallets (user_id, chain, address, label, category, weight, notes) values
  (null, 'ethereum', '0x28C6c06298d514Db089934071355E5743bf21d60', 'Binance Hot 1',  'exchange', 9, 'Largest Binance hot wallet'),
  (null, 'ethereum', '0x71660c4005BA85c37ccec55d0C4493E66Fe775d3', 'Coinbase 1',     'exchange', 9, 'Coinbase main hot'),
  (null, 'ethereum', '0x21a31Ee1afC51d94C2eFcCAa2092aD1028285549', 'Binance 15',     'exchange', 8, 'Binance withdrawal cluster'),
  (null, 'ethereum', '0x2910543Af39abA0Cd09dBb2D50200b3E800A63D2', 'Kraken 1',       'exchange', 7, 'Kraken hot'),
  (null, 'ethereum', '0xD24400ae8BfEBb18cA49Be86258a3C749cf46853', 'Gemini',         'exchange', 6, 'Gemini operations'),
  (null, 'ethereum', '0xDFd5293D8e347dFe59E90eFd55b2956a1343963d', 'Binance 16',     'exchange', 7, 'Binance second cluster'),
  (null, 'ethereum', '0x5a52E96BAcdaBb82fd05763E25335261B270Efcb', 'Binance Cold',   'exchange', 9, 'Cold storage = institutional event'),
  (null, 'ethereum', '0x8484Ef722627bf18ca5Ae6BcF031c23E6e922B30', 'Tether Treasury','treasury', 9, 'USDT mint/burn — capital flow proxy')
on conflict (chain, address, user_id) do nothing;

-- ---------- 011_audit_triggers.sql ----------
-- =============================================================================
-- Migration 011 — Auto-write audit_log triggers for AI/user-data tables.
--
-- The audit_log table exists since 001 but until now nothing writes to it from
-- application code. Per CLAUDE.md §8.6 every AI action must produce an audit
-- trail; the durable way to do that is at the database layer so a forgetful
-- caller cannot bypass it.
--
-- Triggers fire AFTER INSERT/UPDATE/DELETE on:
--   briefs, alerts, ai_calls, exchange_keys, holdings, theses
-- Each trigger writes a single audit_log row capturing the actor (best effort
-- from auth.uid()), the action, target table+pk, and a small summary jsonb.
-- =============================================================================

-- Generic audit-row builder. Each trigger passes (action, target_table, args).
create or replace function audit_log_write(
    p_action text,
    p_target text,
    p_args   jsonb default '{}'::jsonb,
    p_result jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
as $$
declare
    v_uid uuid := nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
begin
    insert into audit_log (user_id, actor, action, target, args_summary, result_summary)
    values (v_uid, case when v_uid is null then 'system' else 'user' end,
            p_action, p_target, p_args, p_result);
exception when others then
    -- Never let an audit failure block the underlying mutation.
    null;
end;
$$;

-- Generic AFTER trigger payload — uses TG_OP, TG_TABLE_NAME, NEW/OLD ids.
create or replace function audit_log_trg() returns trigger
language plpgsql
security definer
as $$
declare
    v_pk text;
    v_args jsonb;
begin
    if (TG_OP = 'DELETE') then
        v_pk := coalesce(OLD.id::text, '');
        v_args := jsonb_build_object('op', TG_OP, 'pk', v_pk);
    else
        v_pk := coalesce(NEW.id::text, '');
        v_args := jsonb_build_object('op', TG_OP, 'pk', v_pk);
    end if;
    perform audit_log_write(TG_OP || ':' || TG_TABLE_NAME, TG_TABLE_NAME, v_args);
    if (TG_OP = 'DELETE') then return OLD; else return NEW; end if;
end;
$$;

-- Wire the trigger to each tracked table. Use DO-block so we silently skip
-- tables that don't exist yet in fresh checkouts (e.g., ai_calls in unit dbs).
do $$
declare
    t text;
begin
    for t in select unnest(array['briefs','alerts','ai_calls','exchange_keys','holdings','theses'])
    loop
        if exists (select 1 from information_schema.tables where table_name = t) then
            execute format('drop trigger if exists audit_%I on %I', t, t);
            execute format(
                'create trigger audit_%I after insert or update or delete on %I '
                'for each row execute function audit_log_trg()', t, t);
        end if;
    end loop;
end $$;

-- ---------- 012_telegram_snooze.sql ----------
-- =============================================================================
-- 012 — Telegram snooze column on users
--
-- Adds `alerts_snoozed_until` so the /snooze command from the Telegram bot
-- can pause alert delivery without dropping rules. The alert_dispatcher
-- worker checks this before sending; the bot's /status command surfaces it.
-- =============================================================================

alter table users
    add column if not exists alerts_snoozed_until timestamptz;

create index if not exists users_telegram_chat_id_idx
    on users (telegram_chat_id)
    where telegram_chat_id is not null;

-- ---------- 013_ta_snapshots.sql ----------
-- =============================================================================
-- 013 — Token Technical-Analysis snapshots, captured at multiple timeframes.
--
-- The TA snapshotter worker writes one row per (token, timeframe, captured_at)
-- on a rolling cadence (1h / 3h / 6h / 12h). The /api/tokens/{symbol}/ta
-- endpoint returns the latest row per timeframe; the token deep-dive page
-- renders a 4-up panel showing how each TF reads the same chart.
-- =============================================================================

create table if not exists token_ta_snapshots (
    id              uuid primary key default uuid_generate_v4(),
    token_id        uuid not null references tokens(id) on delete cascade,
    symbol          text not null,           -- denormalized for fast filter
    timeframe       text not null check (timeframe in ('1h','3h','6h','12h','1d')),
    captured_at     timestamptz not null default now(),
    -- Compact decision fields (the verdict the worker decided)
    stance          text not null check (stance in ('long','short','neutral','no-data')),
    confidence      numeric(4,3),            -- 0..1
    composite_score numeric(5,2),            -- 0..10
    -- Reference levels for entry / risk planning
    last_price      numeric(28,8),
    suggested_entry numeric(28,8),
    suggested_stop  numeric(28,8),
    suggested_target numeric(28,8),
    risk_reward     numeric(6,2),
    atr_pct         numeric(6,3),
    -- Indicator + pattern + structure summary as jsonb so the schema doesn't
    -- have to evolve every time we add a new feature.
    summary         jsonb not null default '{}'::jsonb,
    -- Free-form analyst notes (which patterns hit, which divergences, etc).
    rationale       text[],
    unique (token_id, timeframe, captured_at)
);
create index if not exists ta_snapshots_token_tf_ts on token_ta_snapshots (token_id, timeframe, captured_at desc);
create index if not exists ta_snapshots_symbol_tf_ts on token_ta_snapshots (symbol, timeframe, captured_at desc);
create index if not exists ta_snapshots_recent on token_ta_snapshots (captured_at desc);

-- Public-read; the data is non-PII and the same numbers anyone can compute
-- from public OHLCV. Writes only via service-role (workers).
alter table token_ta_snapshots enable row level security;
create policy "ta_snapshots public read" on token_ta_snapshots
  for select using (true);

-- =============================================================================
-- Trading-bot decisions: one row per (token, cycle), composed from every
-- signal we have. The bot worker writes here every hour.
-- =============================================================================
create table if not exists bot_decisions (
    id              uuid primary key default uuid_generate_v4(),
    token_id        uuid not null references tokens(id) on delete cascade,
    symbol          text not null,
    decided_at      timestamptz not null default now(),
    horizon         text not null check (horizon in ('swing','position','long')),
    stance          text not null check (stance in ('long','short','neutral','watch')),
    confidence      numeric(4,3),            -- 0..1
    composite_score numeric(5,2),            -- 0..10
    -- Risk plan
    last_price      numeric(28,8),
    suggested_entry numeric(28,8),
    suggested_stop  numeric(28,8),
    suggested_target numeric(28,8),
    risk_reward     numeric(6,2),
    -- Inputs that fed the decision (so we can audit / explain)
    inputs          jsonb not null default '{}'::jsonb,
    -- Human-readable reasoning bullets
    reasoning       text[],
    -- Hard invalidation conditions (what would flip this decision)
    invalidation    text[]
);
create index if not exists bot_decisions_token_ts on bot_decisions (token_id, decided_at desc);
create index if not exists bot_decisions_symbol_ts on bot_decisions (symbol, decided_at desc);

alter table bot_decisions enable row level security;
create policy "bot_decisions public read" on bot_decisions
  for select using (true);
